info:
  app:
    name: pizzabakeren-api
    description: Pizzabakeren API

#endpoints:
#  restart:
#    enabled: true
#  refresh:
#    enabled: true

server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pizzabakeren